version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: password123!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - testnetwork

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - testnetwork
    entrypoint: "azurite-blob --blobHost 0.0.0.0"

  python-app:
    image: python:3.10-buster
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - azurite
    networks:
      - testnetwork
    command: ./integration_tests_entrypoint.sh

networks:
  testnetwork:
