version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: password123!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - testnetwork

  python-app:
    image: python:3.10-buster
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - testnetwork
    command: ./integration_tests_entrypoint.sh

networks:
  testnetwork:
